# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  releases-linux:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64, arm]
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.5.linux-amd64.tar.gz"
        binary_name: "go-quickswitch"
        ldflags: -X "main.version=${{ env.APP_VERSION }}"
        extra_files: LICENSE README.md
  release-darwin:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.5.linux-amd64.tar.gz"
        binary_name: "go-quickswitch"
        ldflags: -X "main.version=${{ env.APP_VERSION }}"
        extra_files: LICENSE README.md
  releases-windows:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386", amd64, arm]
    steps:
    - uses: actions/checkout@v2
    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.5.linux-amd64.tar.gz"
        binary_name: "go-quickswitch"
        ldflags: -X "main.version=${{ env.APP_VERSION }}"
        extra_files: LICENSE README.md
